// ═══════════════════════════════════════════════════════════════
//  Questions_AAQ_Unit2_Cyber.gs
//  Question bank for AAQ IT Unit 2 – Cyber Security & Incident Management
//  ~20 questions per activity type. Code.gs selects 10 randomly per session.
// ═══════════════════════════════════════════════════════════════

function getQuestions_AAQ_Unit2_Cyber() {
  return {
    quizKey:  "cyber",
    quizName: "AAQ IT Unit 2 – Cyber Security & Incident Management",

    // ── FILL IN THE BLANKS ──────────────────────────────────
    // Each item: { id, sentence, answer, before, after }
    // 'before' = text before the blank, 'after' = text after
    fitb: [
      { id:"c_f01", answer:"phishing",
        before:"", after:" is a type of attack where a cybercriminal sends a deceptive email pretending to be a trustworthy source in order to steal sensitive information." },
      { id:"c_f02", answer:"malware",
        before:"Software specifically designed to disrupt, damage, or gain unauthorised access to a computer system is known as ", after:"." },
      { id:"c_f03", answer:"DDoS",
        before:"A ", after:" attack overwhelms a server with traffic from multiple sources, making a service unavailable to legitimate users." },
      { id:"c_f04", answer:"ransomware",
        before:"", after:" encrypts a victim's files and demands payment in exchange for the decryption key." },
      { id:"c_f05", answer:"vulnerability",
        before:"A ", after:" is a weakness in a system that can be exploited by an attacker to gain unauthorised access." },
      { id:"c_f06", answer:"firewall",
        before:"A ", after:" monitors and controls incoming and outgoing network traffic based on predetermined security rules." },
      { id:"c_f07", answer:"encryption",
        before:"", after:" transforms data into an unreadable format so only authorised users with the correct key can read it." },
      { id:"c_f08", answer:"patch",
        before:"A software ", after:" is an update released to fix known security vulnerabilities in an application or operating system." },
      { id:"c_f09", answer:"brute force",
        before:"A ", after:" attack tries every possible password combination until the correct one is found." },
      { id:"c_f10", answer:"penetration testing",
        before:"", after:" is an authorised simulated attack on a system to identify vulnerabilities before a real attacker does." },
      { id:"c_f11", answer:"intrusion detection",
        before:"An ", after:" system (IDS) monitors network traffic for suspicious activity and alerts administrators to potential threats." },
      { id:"c_f12", answer:"two-factor authentication",
        before:"", after:" requires users to verify identity using two separate methods, such as a password plus a one-time code." },
      { id:"c_f13", answer:"social engineering",
        before:"", after:" is a technique where attackers manipulate people psychologically rather than exploiting technical vulnerabilities." },
      { id:"c_f14", answer:"incident response",
        before:"An ", after:" plan is a documented set of procedures an organisation follows when a security breach is detected." },
      { id:"c_f15", answer:"spyware",
        before:"", after:" is malware that secretly monitors user activity and sends information back to the attacker without the user's knowledge." },
      { id:"c_f16", answer:"keylogger",
        before:"A ", after:" is a type of malware that records every keystroke made on a device, capturing passwords and confidential data." },
      { id:"c_f17", answer:"DMZ",
        before:"A ", after:" (Demilitarised Zone) is a network segment that sits between an organisation's internal network and the internet, hosting public-facing services." },
      { id:"c_f18", answer:"zero-day",
        before:"A ", after:" exploit targets a software vulnerability on the same day it is discovered, before the developer has released a fix." },
      { id:"c_f19", answer:"VPN",
        before:"A ", after:" (Virtual Private Network) creates an encrypted tunnel over the internet, allowing users to securely access a private network remotely." },
      { id:"c_f20", answer:"risk assessment",
        before:"A ", after:" is the process of identifying, analysing, and evaluating threats and vulnerabilities to determine appropriate countermeasures." },
    ],

    // ── MATCHING ─────────────────────────────────────────────
    // Each item: { id, term, definition }
    match: [
      { id:"c_m01", term:"Phishing",         definition:"A fraudulent attempt to steal sensitive information by impersonating a trusted entity in electronic communication." },
      { id:"c_m02", term:"SQL Injection",     definition:"An attack that inserts malicious code into a database query to manipulate or extract data." },
      { id:"c_m03", term:"Trojan",            definition:"Malware disguised as legitimate software that creates a backdoor into a system." },
      { id:"c_m04", term:"Keylogger",         definition:"Software that records every keystroke made on a device, capturing passwords and confidential input." },
      { id:"c_m05", term:"Spyware",           definition:"Software that secretly monitors and collects user activity without the user's consent." },
      { id:"c_m06", term:"Encryption",        definition:"Converting data into a coded format so only someone with the correct key can read it." },
      { id:"c_m07", term:"DMZ",               definition:"A network segment between an organisation's internal network and the internet, hosting public-facing services." },
      { id:"c_m08", term:"Zero-day exploit",  definition:"An attack targeting a software vulnerability on the same day it is discovered, before a fix exists." },
      { id:"c_m09", term:"Risk assessment",   definition:"Identifying, analysing, and evaluating threats and vulnerabilities to determine appropriate countermeasures." },
      { id:"c_m10", term:"Disaster recovery", definition:"A documented set of procedures to restore IT systems following a major disruption or attack." },
      { id:"c_m11", term:"Ransomware",        definition:"Malware that encrypts a victim's files and demands payment before restoring access." },
      { id:"c_m12", term:"Firewall",          definition:"A system that monitors and controls incoming and outgoing network traffic based on security rules." },
      { id:"c_m13", term:"Brute force",       definition:"An attack that systematically tries every possible password combination until the correct one is found." },
      { id:"c_m14", term:"Social engineering",definition:"Manipulating people psychologically to reveal confidential information or perform actions that compromise security." },
      { id:"c_m15", term:"IDS",               definition:"A system that monitors network traffic for suspicious activity and alerts administrators to potential threats." },
      { id:"c_m16", term:"VPN",               definition:"Creates an encrypted tunnel over the internet, allowing secure remote access to a private network." },
      { id:"c_m17", term:"Penetration testing",definition:"An authorised simulated attack on a system carried out to identify and evaluate vulnerabilities." },
      { id:"c_m18", term:"Patch",             definition:"A software update released by developers to fix known security vulnerabilities or bugs." },
      { id:"c_m19", term:"Smishing",          definition:"A phishing attack carried out via SMS text messages rather than email." },
      { id:"c_m20", term:"Whaling",           definition:"A targeted phishing attack aimed specifically at senior executives or high-value individuals within an organisation." },
    ],

    // ── MULTIPLE CHOICE ──────────────────────────────────────
    // Each item: { id, question, options:[{label,text}], answer }
    mc: [
      { id:"c_mc01", question:"Which type of attack uses a network of compromised computers to flood a server with traffic?",
        options:[{l:"A",t:"Phishing attack"},{l:"B",t:"Distributed Denial of Service (DDoS)"},{l:"C",t:"Man-in-the-middle attack"},{l:"D",t:"Brute force attack"}], answer:"B" },
      { id:"c_mc02", question:"A hacker sends a text message pretending to be a bank. What type of attack is this?",
        options:[{l:"A",t:"Vishing"},{l:"B",t:"Smishing"},{l:"C",t:"Spear phishing"},{l:"D",t:"Whaling"}], answer:"B" },
      { id:"c_mc03", question:"Which best describes a man-in-the-middle attack?",
        options:[{l:"A",t:"Installing malware while the owner is absent."},{l:"B",t:"Intercepting communication between two parties without their knowledge."},{l:"C",t:"Creating a fake social media profile to gain trust."},{l:"D",t:"Sending spam emails to overwhelm a server."}], answer:"B" },
      { id:"c_mc04", question:"Which sits between an organisation's internal network and the internet, filtering traffic?",
        options:[{l:"A",t:"IDS (Intrusion Detection System)"},{l:"B",t:"VPN (Virtual Private Network)"},{l:"C",t:"Firewall"},{l:"D",t:"DMZ (Demilitarised Zone)"}], answer:"C" },
      { id:"c_mc05", question:"What is the PRIMARY purpose of regularly applying software patches?",
        options:[{l:"A",t:"To improve the graphical user interface."},{l:"B",t:"To fix known security vulnerabilities and reduce exploitation risk."},{l:"C",t:"To increase internet connection speed."},{l:"D",t:"To automatically back up user data."}], answer:"B" },
      { id:"c_mc06", question:"Passwords stored using a hash function means they are:",
        options:[{l:"A",t:"Stored in plain text for easy retrieval."},{l:"B",t:"Deleted automatically after a set period."},{l:"C",t:"Converted into a fixed-length string that cannot be reversed."},{l:"D",t:"Encrypted and decryptable by the IT team."}], answer:"C" },
      { id:"c_mc07", question:"Which is the correct order of steps in an incident response plan?",
        options:[{l:"A",t:"Eradication → Identification → Containment → Recovery → Lessons learned"},{l:"B",t:"Identification → Containment → Eradication → Recovery → Lessons learned"},{l:"C",t:"Containment → Identification → Recovery → Eradication → Lessons learned"},{l:"D",t:"Identification → Eradication → Containment → Lessons learned → Recovery"}], answer:"B" },
      { id:"c_mc08", question:"Under UK GDPR, within how many hours must a personal data breach be reported to the ICO?",
        options:[{l:"A",t:"24 hours"},{l:"B",t:"48 hours"},{l:"C",t:"72 hours"},{l:"D",t:"7 days"}], answer:"C" },
      { id:"c_mc09", question:"Which Act makes it a criminal offence to access computer systems without authorisation?",
        options:[{l:"A",t:"Data Protection Act 2018"},{l:"B",t:"Copyright, Designs and Patents Act 1988"},{l:"C",t:"Computer Misuse Act 1990"},{l:"D",t:"Investigatory Powers Act 2016"}], answer:"C" },
      { id:"c_mc10", question:"What is spear phishing?",
        options:[{l:"A",t:"A mass phishing email sent to millions of random recipients."},{l:"B",t:"A phishing attack sent via SMS."},{l:"C",t:"A targeted phishing attack aimed at a specific individual or organisation."},{l:"D",t:"A phishing attack that uses voice calls."}], answer:"C" },
      { id:"c_mc11", question:"Which of the following BEST describes a zero-day vulnerability?",
        options:[{l:"A",t:"A vulnerability that has already been patched."},{l:"B",t:"A vulnerability in software that is unknown to the vendor and has no patch available."},{l:"C",t:"A vulnerability that only affects zero users."},{l:"D",t:"A vulnerability caused by weak passwords."}], answer:"B" },
      { id:"c_mc12", question:"What does a VPN primarily provide?",
        options:[{l:"A",t:"Faster internet speeds."},{l:"B",t:"A secure, encrypted connection over a public network."},{l:"C",t:"Protection against viruses on a local device."},{l:"D",t:"A backup of all user files."}], answer:"B" },
      { id:"c_mc13", question:"An attacker calls an employee pretending to be IT support to obtain a password. What type of attack is this?",
        options:[{l:"A",t:"Phishing"},{l:"B",t:"Smishing"},{l:"C",t:"Vishing"},{l:"D",t:"Whaling"}], answer:"C" },
      { id:"c_mc14", question:"Which security measure checks all incoming and outgoing packets and blocks those that don't meet security rules?",
        options:[{l:"A",t:"Antivirus software"},{l:"B",t:"Encryption"},{l:"C",t:"Firewall"},{l:"D",t:"Two-factor authentication"}], answer:"C" },
      { id:"c_mc15", question:"What is the purpose of the 'lessons learned' phase in an incident response plan?",
        options:[{l:"A",t:"To identify and contain the threat."},{l:"B",t:"To restore systems to normal operation."},{l:"C",t:"To review what happened and improve future responses."},{l:"D",t:"To notify affected users of the breach."}], answer:"C" },
      { id:"c_mc16", question:"Which type of malware disguises itself as legitimate software to trick users into installing it?",
        options:[{l:"A",t:"Worm"},{l:"B",t:"Ransomware"},{l:"C",t:"Trojan"},{l:"D",t:"Spyware"}], answer:"C" },
      { id:"c_mc17", question:"What is the main difference between symmetric and asymmetric encryption?",
        options:[{l:"A",t:"Symmetric uses two keys; asymmetric uses one."},{l:"B",t:"Symmetric uses one shared key; asymmetric uses a public and private key pair."},{l:"C",t:"Symmetric is less secure than asymmetric."},{l:"D",t:"Asymmetric is faster than symmetric."}], answer:"B" },
      { id:"c_mc18", question:"Which of the following is an example of a physical security control?",
        options:[{l:"A",t:"Installing antivirus software."},{l:"B",t:"Using a firewall."},{l:"C",t:"Locking server rooms and using key card access."},{l:"D",t:"Enforcing strong password policies."}], answer:"C" },
      { id:"c_mc19", question:"What does 'containment' mean in the context of incident response?",
        options:[{l:"A",t:"Permanently removing the threat from all systems."},{l:"B",t:"Limiting the spread and impact of a security incident."},{l:"C",t:"Restoring systems to their pre-incident state."},{l:"D",t:"Reporting the incident to senior management."}], answer:"B" },
      { id:"c_mc20", question:"An organisation stores customer credit card data. Under PCI DSS, what must they do to protect stored card data?",
        options:[{l:"A",t:"Delete it after 24 hours."},{l:"B",t:"Store it in plain text with restricted access."},{l:"C",t:"Encrypt it using strong cryptographic methods."},{l:"D",t:"Back it up to a cloud service."}], answer:"C" },
    ],

    // ── TRUE OR FALSE ────────────────────────────────────────
    // Each item: { id, statement, answer }
    tf: [
      { id:"c_t01", statement:"Phishing attacks are exclusively carried out through email.", answer:false },
      { id:"c_t02", statement:"A zero-day vulnerability is one that has already been patched by the software developer.", answer:false },
      { id:"c_t03", statement:"Ransomware typically encrypts a victim's files and demands payment before restoring access.", answer:true },
      { id:"c_t04", statement:"Social engineering attacks exploit technical software flaws rather than human psychology.", answer:false },
      { id:"c_t05", statement:"Using HTTPS protects data in transit between a browser and a web server.", answer:true },
      { id:"c_t06", statement:"A firewall can always prevent a breach caused by an authorised insider leaking information.", answer:false },
      { id:"c_t07", statement:"Penetration testing involves an authorised tester simulating attacks to find system weaknesses.", answer:true },
      { id:"c_t08", statement:"The 'lessons learned' phase of incident response happens before containment.", answer:false },
      { id:"c_t09", statement:"Multi-factor authentication (MFA) uses two or more verification methods to confirm identity.", answer:true },
      { id:"c_t10", statement:"The Computer Misuse Act 1990 makes it legal to access systems without permission, as long as no damage is caused.", answer:false },
      { id:"c_t11", statement:"A DDoS attack uses a single computer to flood a server with requests.", answer:false },
      { id:"c_t12", statement:"Encryption makes data unreadable without the correct decryption key.", answer:true },
      { id:"c_t13", statement:"A VPN hides a user's IP address and encrypts their internet traffic.", answer:true },
      { id:"c_t14", statement:"Smishing is a phishing attack carried out via phone calls.", answer:false },
      { id:"c_t15", statement:"Regular software patching is one of the most effective ways to reduce vulnerability to cyber attacks.", answer:true },
      { id:"c_t16", statement:"A Trojan horse virus replicates itself and spreads across a network automatically.", answer:false },
      { id:"c_t17", statement:"Two-factor authentication is more secure than a single password alone.", answer:true },
      { id:"c_t18", statement:"The purpose of a DMZ is to provide a buffer zone between the public internet and an organisation's internal network.", answer:true },
      { id:"c_t19", statement:"Whaling attacks target junior employees who are most likely to click suspicious links.", answer:false },
      { id:"c_t20", statement:"UK GDPR requires organisations to report qualifying data breaches to the ICO within 72 hours.", answer:true },
    ]
  };
}
